### ISSUE TITLE
expected SSA operand

### ISSUE THREAD

**Issue by raikonenfnu** [polymage-labs/mlirx#11]
Hey guys, I am trying to run dgemm-hop.mlir but seems to face some error:

This is my command:

`/bin/mlir-opt -hopt -convert-linalg-to-loops -lower-affine -convert-std-to-llvm ../mlir/benchmark/sgemm-tiled-benchmark.mlir`

  Expected Behaviour:
  Generate llvm code

This is the error received:
`../mlir/benchmark/sgemm-tiled-benchmark.mlir:24:16: error: expected SSA operand
  %M = dim %C, 0 : memref<2088x2048xf32>`
  
  Thanks in advance for your help guys! :)

**Comment by raikonenfnu** [comment]
Also when I comment those parts out, I got this error:

`../mlir/benchmark/dgemm-hop.mlir:45:1: error: 'func' op symbol declaration cannot have public visibility
func @rtclock() -> (f64)
^
../mlir/benchmark/dgemm-hop.mlir:45:1: note: see current operation: "func"() ( {
}) {sym_name = "rtclock", type = () -> f64} : () -> ()`

**Comment by bondhugula** [comment]
This looks like the benchmarks weren't updated to the new spec for `DimOp` and visibility attribute related changes for ops. I'll fix this in the next few minutes.

**Comment by raikonenfnu** [comment]
awesome! Thanks for the quick response and help Uday! :)

**Comment by bondhugula** [comment]
Fixed - thanks for reporting. Btw, you can't just use `-convert-std-to-llvm` right after lowering Affine to SCF. You need `-convert-scf-to-std` in between. The README had the old name `-convert-loop-to-std` which I have also fixed.

**Comment by bondhugula** [comment]
Fixed by 0c72d6a8de318d1127fc1ea8efd2fdcb8ec019dc and 5664f814c83716e55159ce52ecab328a319c05b3

**Comment by bondhugula** [comment]
```bin/mlir-opt -hopt -convert-linalg-to-loops -lower-affine -convert-scf-to-std -convert-std-to-llvm  ../mlir/benchmark/sgemm-tiled-benchmark.mlir``` works now.

**Comment by raikonenfnu** [comment]
tested it, and it works, thanks Uday!
