### ISSUE TITLE
Materials from the publication/paper

### ISSUE THREAD

**Issue by raikonenfnu** [polymage-labs/mlirx#12]
Hey guys,

Does anybody know where to find the hop branch, and other material such used  such as the matmul program generated by blis/openblas/mkl? Thanks in advance!

**Comment by bondhugula** [comment]
`blis` could just downloaded and installed from its official repo. `openblas` is available with all major Linux distribution repos. For eg. `dnf -y install openblas-devel` on Fedora and CentOS. MKL is available from Intel freely. `mlirx` master branch is the right place (as opposed to the `hop` branch which isn't maintained to be in sync with upstream MLIR).

**Comment by raikonenfnu** [comment]
I see, I am particularly interested in recreating the results for hopt vs hopt-blis. Looking at the hopt transform from lib/Transforms/HigherOrderPolyhedralOpt.cpp, it looks like it already include hopt optimization, copying, unrolling, and scalrep. But I was wondering if there is a way we can obtain the mlir file generated from hopt-blis. Thanks in advance, and Happy holidays :)
