### ISSUE TITLE
mlir benchmark: failed to legalize operation 'hop.matmul'

### ISSUE THREAD

**Issue by runzhech** [polymage-labs/mlirx#20]
I've followed the instrunctions at the top of the **mlir/benchmark/dgemm-hop.mlir**, 
` mlir-opt -hopt -convert-linalg-to-llvm -lower-affine -convert-std-to-llvm ./dgemm-hop.mlir | mlir-cpu-runner -O3 -e main -entry-point-result=void -shared-libs=../../build/lib/libmlir_runner_utils.so`
and I encounted an error that
```
./dgemm-hop.mlir:50:3: error: failed to legalize operation 'hop.matmul'
  "hop.matmul"(%arg0, %arg1, %arg2) {
  ^
Error: entry point not found
```
It seems that it needs a **hop** Dialect, but I didn't find it in the repo.
May anyone give me some advice?

**Comment by bondhugula** [comment]
The "hop.matmul" is meant to be an unregistered operation. There is no separate `hop` dialect. Thank you for reporting this. I'll update the instructions.

**Comment by bondhugula** [comment]
> The "hop.matmul" is meant to be an unregistered operation. There is no separate `hop` dialect. Thank you for reporting this. I'll update the instructions.

The example and the codebase require a few modernization fixes. We'll fix this in a few hours.

**Comment by bondhugula** [comment]
> 

The instructions are actually in the README.md file. The file to use for testing out of the box is `benchmark/dgemm-tiled-benchmark.mlir`. dgemm-hop.mlir was meant to be an exercise to complete. The following will work:

```
bin/mlir-opt ../mlir/benchmark/dgemm-tiled-benchmark.mlir \
    -hopt='vect=true copy=true unroll=true scalrep=true' \
    -convert-linalg-to-loops -lower-affine -convert-scf-to-std \
    -convert-memref-to-llvm='use-aligned-alloc=1' -convert-std-to-llvm \
    -canonicalize \
    | bin/mlir-cpu-runner  -O3  -e main -time -reps=5 -entry-point-result=void \
    -shared-libs=lib/libmlir_runner_utils.so \
    -shared-libs=lib/libmlir_c_runner_utils.so > /dev/null
```

**Comment by runzhech** [comment]
> > 
> 
> The instructions are actually in the README.md file. The file to use for testing out of the box is `benchmark/dgemm-tiled-benchmark.mlir`. dgemm-hop.mlir was meant to be an exercise to complete. The following will work:
> 
> ```
> bin/mlir-opt ../mlir/benchmark/dgemm-tiled-benchmark.mlir \
>     -hopt='vect=true copy=true unroll=true scalrep=true' \
>     -convert-linalg-to-loops -lower-affine -convert-scf-to-std \
>     -convert-memref-to-llvm='use-aligned-alloc=1' -convert-std-to-llvm \
>     -canonicalize \
>     | bin/mlir-cpu-runner  -O3  -e main -time -reps=5 -entry-point-result=void \
>     -shared-libs=lib/libmlir_runner_utils.so \
>     -shared-libs=lib/libmlir_c_runner_utils.so > /dev/null
> ```

This command works on my env, thanks for your help.
